### ISSUE TITLE
按返回键，在后台运行时服务会被stop掉

### ISSUE THREAD

**Issue by wenfengtou** [wenfengtou/BedWatching#1]
Stopping service due to app idle
打出类似这样的log

**Comment by wenfengtou** [comment]
*APP* UID 10147 ProcessRecord{e05de15 20994:com.wenfengtou.bedwatching/u0a147}
    user #0 uid=10147 gids={50147, 20147, 9997, 3003}
    requiredAbi=arm64-v8a instructionSet=null
    class=com.wenfengtou.bedwatching.BedWatchingApplication
    dir=/data/app/com.wenfengtou.bedwatching-mn6YljI_Qga9B5D1B1QGOA==/base.apk publicDir=/data/app/com.wenfengtou.bedwatching-mn6YljI_Qga9B5D1B1QGOA==/base.apk data=/data/user/0/com.wenfengtou.bedwatching
    packageList={com.wenfengtou.bedwatching}
    compat={480dpi}
    thread=android.app.IApplicationThread$Stub$Proxy@bd1b359
    pid=20994 starting=false
    lastActivityTime=-2m34s123ms lastPssTime=-12s715ms nextPssTime=+29m47s4ms
    adjSeq=4225 lruSeq=0 lastPss=47MB lastSwapPss=0.00 lastCachedPss=47MB lastCachedSwapPss=0.00
    cached=true empty=true
    oom: max=1001 curRaw=900 setRaw=900 cur=900 set=900
    curSchedGroup=0 setSchedGroup=0 systemNoUi=false trimMemoryLevel=0
    curProcState=17 repProcState=17 pssProcState=17 setProcState=17 lastStateTime=-1m33s947ms
    hasShownUi=true pendingUiClean=false hasAboveClient=false treatLikeActivity=false
    lastCpuTime=0 whenUnimportant=-2m34s123ms
    lastRequestedGc=-2m44s783ms lastLowMemory=-2m44s783ms reportLowMemory=false
    Connected Providers:
      - 349b3e9/com.android.providers.settings/.SettingsProvider->20994:com.wenfengtou.bedwatching/u0a147 s1/1 u0/0 +2m44s564ms
    Receivers:
      - ReceiverList{92c2f82 20994 com.wenfengtou.bedwatching/10147/u0 remote:b74bacd}

进程状态变成了17，cache_empty状态了。

**Comment by wenfengtou** [comment]
01-01 16:02:01.349 16897 18415 I ActivityManager: Changes in UidRecord{e17d51e u0a147 CEM  bg:+1m0s218ms idle change:idle procs:1 seq(0,0,0)}: proc state from 11 to 17, whitelist from false to false
01-01 16:02:01.349 16897 18415 I ActivityManager: java.lang.Throwable
01-01 16:02:01.349 16897 18415 I ActivityManager:       at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:26542)
01-01 16:02:01.349 16897 18415 I ActivityManager:       at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:25978)
01-01 16:02:01.349 16897 18415 I ActivityManager:       at com.android.server.am.ActiveServices.serviceDoneExecutingLocked(ActiveServices.java:3249)
01-01 16:02:01.349 16897 18415 I ActivityManager:       at com.android.server.am.ActiveServices.serviceDoneExecutingLocked(ActiveServices.java:3192)
01-01 16:02:01.349 16897 18415 I ActivityManager:       at com.android.server.am.ActivityManagerService.serviceDoneExecuting(ActivityManagerService.java:21335)
01-01 16:02:01.349 16897 18415 I ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:952)
01-01 16:02:01.349 16897 18415 I ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3392)
01-01 16:02:01.349 16897 18415 I ActivityManager:       at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:574)
01-01 16:02:01.349 16897 18415 I ActivityManager:       at android.os.Binder.execTransact(Binder.java:697)

服务执行完了，updateOomAdjLocked，进程状态从11变成了17.从state-service变成了cache-empty。

**Comment by wenfengtou** [comment]
上楼错了，上楼是服务被杀之后的情况。

分析如下
01-01 16:01:01.235 16897 16938 I ActivityManager: Changes in UidRecord{e17d51e u0a147 SVC  change:active|uncached procs:1 seq(0,0,0)}: proc state from 2 to 11, whitelist from false to false
状态有top变成了service
01-01 16:02:01.349 16897 18415 I ActivityManager: Changes in UidRecord{e17d51e u0a147 CEM  bg:+1m0s218ms idle change:idle procs:1 seq(0,0,0)}: proc state from 11 to 17, whitelist from false to false
再由service变成了cache-empty
