### ISSUE TITLE
多次点击按钮崩溃

### ISSUE THREAD

**Issue by wenfengtou** [wenfengtou/BedWatching#3]

**Comment by wenfengtou** [comment]
04-12 03:40:52.704 27146 27146 E AndroidRuntime: java.lang.IllegalArgumentException: Service not registered: com.wenfengtou.bedwatching.MainActivity$1@28d237d
04-12 03:40:52.704 27146 27146 E AndroidRuntime: 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1289)
04-12 03:40:52.704 27146 27146 E AndroidRuntime: 	at android.app.ContextImpl.unbindService(ContextImpl.java:1483)
04-12 03:40:52.704 27146 27146 E AndroidRuntime: 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
04-12 03:40:52.704 27146 27146 E AndroidRuntime: 	at com.wenfengtou.bedwatching.MainActivity.stopBedWatching(MainActivity.java:221)

查看堆栈，是在unbind的时候报错，服务还没bind的时候就unbind所以报错了。解决办法是stopBedWatching函数的时候，不需要unbind。

**Comment by wenfengtou** [comment]
修改链接：
https://github.com/wenfengtou/BedWatching/commit/1c2c247dad1e126913c7c49b52f56d5e845afd2c
